/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.carroController;
import Model.carroModel;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilherme
 */
public class FRM_PesquisasAvancadas extends javax.swing.JFrame {

    /**
     * Creates new form FRM_PesquisasAvancadas
     */
    public FRM_PesquisasAvancadas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        TXT_MarcaDigitada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        BNT_PesquisarPorMarca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ConsultaTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXT_Iniciais = new javax.swing.JTextField();
        BNT_PesquisarIniciais = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXT_Ano = new javax.swing.JTextField();
        BNT_PesquisarPorAno = new javax.swing.JToggleButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Serif Cond", 1, 18)); // NOI18N
        jLabel1.setText("Pesquisar veiculos por Marca");

        jLabel2.setText("Marca:");

        BNT_PesquisarPorMarca.setText("Pesquisar");
        BNT_PesquisarPorMarca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BNT_PesquisarPorMarcaMouseClicked(evt);
            }
        });

        ConsultaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ano", "marca", "modelo", "placa", "cor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ConsultaTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(ConsultaTable);

        jLabel3.setFont(new java.awt.Font("Noto Serif Cond", 1, 18)); // NOI18N
        jLabel3.setText("Pesquisar por Iniciais");

        jLabel4.setText("Placa:");

        BNT_PesquisarIniciais.setText("Pesquisar");
        BNT_PesquisarIniciais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BNT_PesquisarIniciaisMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Noto Serif Cond", 1, 18)); // NOI18N
        jLabel5.setText("Pesquisar por Ano");

        jLabel6.setText("Ano:");

        BNT_PesquisarPorAno.setText("Pesquisar");
        BNT_PesquisarPorAno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BNT_PesquisarPorAnoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BNT_PesquisarPorAno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TXT_Ano))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXT_MarcaDigitada))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BNT_PesquisarPorMarca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXT_Iniciais, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BNT_PesquisarIniciais, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TXT_MarcaDigitada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BNT_PesquisarPorMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TXT_Iniciais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BNT_PesquisarIniciais)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TXT_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BNT_PesquisarPorAno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNT_PesquisarPorMarcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BNT_PesquisarPorMarcaMouseClicked
        String marca = this.TXT_MarcaDigitada.getText();
        DefaultTableModel dados = (DefaultTableModel) ConsultaTable.getModel();
        ArrayList carros = new ArrayList();
        dados.setNumRows(0);
        carroController carCNTR = new carroController();
        carros = carCNTR.buscarCarrosPorMarca(marca);
        Iterator it = carros.iterator();
        while (it.hasNext()){
            carroModel car = (carroModel) it.next();
            dados.addRow(new Object[]{
                car.getAnoFabricacao(),
                car.getMarca(), 
                car.getModelo(),
                car.getPlaca(), 
                car.getCor(), 
            }
            );
            }
    }//GEN-LAST:event_BNT_PesquisarPorMarcaMouseClicked

    private void BNT_PesquisarIniciaisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BNT_PesquisarIniciaisMouseClicked
        String chavePlaca = this.TXT_Iniciais.getText();
        DefaultTableModel dados = (DefaultTableModel) ConsultaTable.getModel();
        ArrayList carros = new ArrayList();
        dados.setNumRows(0);
        carroController carCNTR = new carroController();
        carros = carCNTR.buscarCarrosPorLetra(chavePlaca);
        Iterator it = carros.iterator();
        while (it.hasNext()){
            carroModel car = (carroModel) it.next();
            dados.addRow(new Object[]{
                car.getAnoFabricacao(),
                car.getMarca(), 
                car.getModelo(),
                car.getPlaca(), 
                car.getCor(), 
            }
            );
            }
    }//GEN-LAST:event_BNT_PesquisarIniciaisMouseClicked

    private void BNT_PesquisarPorAnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BNT_PesquisarPorAnoMouseClicked
        int ano = Integer.parseInt(this.TXT_Ano.getText());
        DefaultTableModel dados = (DefaultTableModel) ConsultaTable.getModel();
        ArrayList carros = new ArrayList();
        dados.setNumRows(0);
        carroController carCNTR = new carroController();
        carros = carCNTR.buscarCarrosPorAno(ano);
        Iterator it = carros.iterator();
        while (it.hasNext()){
            carroModel car = (carroModel) it.next();
            dados.addRow(new Object[]{
                car.getAnoFabricacao(),
                car.getMarca(), 
                car.getModelo(),
                car.getPlaca(), 
                car.getCor(), 
            }
            );
            }
    }//GEN-LAST:event_BNT_PesquisarPorAnoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_PesquisasAvancadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_PesquisasAvancadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_PesquisasAvancadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_PesquisasAvancadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_PesquisasAvancadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BNT_PesquisarIniciais;
    private javax.swing.JToggleButton BNT_PesquisarPorAno;
    private javax.swing.JButton BNT_PesquisarPorMarca;
    private javax.swing.JTable ConsultaTable;
    private javax.swing.JTextField TXT_Ano;
    private javax.swing.JTextField TXT_Iniciais;
    private javax.swing.JTextField TXT_MarcaDigitada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
